---
- name: install packages
  apt:
    name:
    - unzip
    update_cache: true
  tags:
  - loki

- name: download loki
  get_url:
    url: "{{ loki_url }}"
    dest: /tmp/loki.zip
  tags:
  - loki

- name: unzip loki
  unarchive:
    src: /tmp/loki.zip
    remote_src: true
    dest: /usr/bin/
    mode: 0755
  tags:
  - loki

- name: template loki service file
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
  tags:
  - loki

- name: template loki config file
  template:
    src: loki.yml.j2
    dest: /etc/loki.yml
  tags:
  - loki

- name: restart service
  systemd:
    name: loki.service
    enabled: true 
    daemon_reload: true 
    state: restarted
  tags:
  - loki