---
- name: install packages
  apt:
    name:
    - unzip
    update_cache: true
  tags:
  - promtail

- name: download promtail
  get_url:
    url: "{{ promtail_url }}"
    dest: /tmp/promtail.zip
  tags:
  - promtail

- name: unzip promtail
  unarchive:
    src: /tmp/promtail.zip
    remote_src: true
    dest: /usr/bin/
    mode: 0755
  tags:
  - promtail

- name: template promtail service file
  template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
  tags:
  - promtail

- name: template promtail config file
  template:
    src: promtail.yml.j2
    dest: /etc/promtail.yml
  tags:
  - promtail

- name: restart service
  systemd:
    name: promtail.service
    enabled: true 
    daemon_reload: true 
    state: restarted
  tags:
  - promtail